package com.vista.dato;

import java.util.HashSet;
import java.util.Set;

import android.content.ContentValues;

/**
 * Favorito generated by hbm2java
 */
public class Favorito implements java.io.Serializable {

	private int cod = -1;
	private String title = "";
	private String descripcion = "";
	private int tipo = -1;
	private int img = -1;

	public Favorito() {
	}

	/**
	 * @return the cod
	 */
	public int getCod() {
		return cod;
	}

	/**
	 * @param cod
	 *            the cod to set
	 */
	public void setCod(int cod) {
		this.cod = cod;
	}

	/**
	 * @return the title
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * @param title
	 *            the title to set
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * @return the descripcion
	 */
	public String getDescripcion() {
		return descripcion;
	}

	/**
	 * @param descripcion
	 *            the descripcion to set
	 */
	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	/**
	 * @return the tipo
	 */
	public int getTipo() {
		return tipo;
	}

	/**
	 * @param tipo
	 *            the tipo to set
	 */
	public void setTipo(int tipo) {
		this.tipo = tipo;
	}

	/**
	 * @return the img
	 */
	public int getImg() {
		return img;
	}

	/**
	 * @param img
	 *            the img to set
	 */
	public void setImg(int img) {
		this.img = img;
	}

	public ContentValues getValues() {
		ContentValues values = new ContentValues();
		if (cod != -1) {
			values.put("cod", cod);
		}
		values.put("title", this.title);
		values.put("descripcion", this.descripcion);
		values.put("tipo", this.tipo);
		values.put("img", this.img);
		return values;
	}

}
