package com.vista.dato;
// Generated 10-06-2013 10:34:05 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Transportador generated by hbm2java
 */
public class Transportador  implements java.io.Serializable {


     private Integer cod;
     private String nombre;
     private String placa;
     private String carga;
     private String estado;
     private Set ventas = new HashSet(0);

    public Transportador() {
    }

	
    public Transportador(String nombre, String placa, String carga, String estado) {
        this.nombre = nombre;
        this.placa = placa;
        this.carga = carga;
        this.estado = estado;
    }
    public Transportador(String nombre, String placa, String carga, String estado, Set ventas) {
       this.nombre = nombre;
       this.placa = placa;
       this.carga = carga;
       this.estado = estado;
       this.ventas = ventas;
    }
   
    public Integer getCod() {
        return this.cod;
    }
    
    public void setCod(Integer cod) {
        this.cod = cod;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getPlaca() {
        return this.placa;
    }
    
    public void setPlaca(String placa) {
        this.placa = placa;
    }
    public String getCarga() {
        return this.carga;
    }
    
    public void setCarga(String carga) {
        this.carga = carga;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Set ventas) {
        this.ventas = ventas;
    }




}


