package com.vista.dato;
// Generated 10-06-2013 10:34:05 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private Integer uid;
     private String uniqueId;
     private String name;
     private String email;
     private String encryptedPassword;
     private String salt;
     private Date createdAt;
     private Date updatedAt;

    public Users() {
    }

	
    public Users(String uniqueId, String name, String email, String encryptedPassword, String salt) {
        this.uniqueId = uniqueId;
        this.name = name;
        this.email = email;
        this.encryptedPassword = encryptedPassword;
        this.salt = salt;
    }
    public Users(String uniqueId, String name, String email, String encryptedPassword, String salt, Date createdAt, Date updatedAt) {
       this.uniqueId = uniqueId;
       this.name = name;
       this.email = email;
       this.encryptedPassword = encryptedPassword;
       this.salt = salt;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
    }
   
    public Integer getUid() {
        return this.uid;
    }
    
    public void setUid(Integer uid) {
        this.uid = uid;
    }
    public String getUniqueId() {
        return this.uniqueId;
    }
    
    public void setUniqueId(String uniqueId) {
        this.uniqueId = uniqueId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getEncryptedPassword() {
        return this.encryptedPassword;
    }
    
    public void setEncryptedPassword(String encryptedPassword) {
        this.encryptedPassword = encryptedPassword;
    }
    public String getSalt() {
        return this.salt;
    }
    
    public void setSalt(String salt) {
        this.salt = salt;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }




}


