package com.vista.dato;

import java.io.IOException;

import org.apache.http.client.ClientProtocolException;
import org.json.JSONException;
import org.json.JSONObject;



import android.content.ContentValues;
import android.content.Context;
import android.database.Cursor;

/**
 * Usuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable {

	private Integer codus=-1;
	private int personal=-1;
	private String nick="";
	private String email="";
	private String encryptedPassword="";
	private String salt="";
	private String creado="";
	private String actualizado="";
	private String estado="";
	//MyHelper helper;
	
	public Usuario() {
		//helper= new MyHelper();
	}

	public Usuario(int personal, String nick, String email,
			String encryptedPassword, String salt, String estado) {
		this.personal = personal;
		this.nick = nick;
		this.email = email;
		this.encryptedPassword = encryptedPassword;
		this.salt = salt;
		this.estado = estado;
	}

	public Usuario(int personal, String nick, String email,
			String encryptedPassword, String salt, String creado,
			String actualizado, String estado) {
		this.personal = personal;
		this.nick = nick;
		this.email = email;
		this.encryptedPassword = encryptedPassword;
		this.salt = salt;
		this.creado = creado;
		this.actualizado = actualizado;
		this.estado = estado;
	}

	public Integer getCodus() {
		return this.codus;
	}

	public void setCodus(Integer codus) {
		this.codus = codus;
	}

	public int getint() {
		return this.personal;
	}

	public void setint(int personal) {
		this.personal = personal;
	}

	public String getNick() {
		return this.nick;
	}

	public void setNick(String nick) {
		this.nick = nick;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getEncryptedPassword() {
		return this.encryptedPassword;
	}

	public void setEncryptedPassword(String encryptedPassword) {
		this.encryptedPassword = encryptedPassword;
	}

	public String getSalt() {
		return this.salt;
	}

	public void setSalt(String salt) {
		this.salt = salt;
	}

	public String getCreado() {
		return this.creado;
	}

	public void setCreado(String creado) {
		this.creado = creado;
	}

	public String getActualizado() {
		return this.actualizado;
	}

	public void setActualizado(String actualizado) {
		this.actualizado = actualizado;
	}

	public String getEstado() {
		return this.estado;
	}
	public void setEstado(String estado) {
		this.estado = estado;
	}
	public void setPersonal(int personal) {
		this.personal = personal;
	}
	public int getPersonal() {
		return this.personal;
	}


	
	public ContentValues getValues() {

		ContentValues values = new ContentValues();
		if (codus != -1) {
			values.put("cod", codus);
		}
		values.put("pers", personal);
		values.put("nick", nick);
		values.put("email", email);
		values.put("encrypted_password", encryptedPassword);
		values.put("salt", salt);
		values.put("actualizado", actualizado);
		values.put("estado", estado);
		return values;
	}
	
//	public void loginback(Context context) throws ClientProtocolException, IOException, JSONException{
//		ParserFunction function= new ParserFunction();
//		MyHelper helper= new MyHelper();
//		Cursor c=helper.getObjects("select max(cod) as cod, pers from usuario", context);
//		JSONObject jsonObject=null;
//		if (c!=null) {
//			c.moveToFirst();
//			String cod = c.getString(c.getColumnIndex("pers"));
//			jsonObject= function.loginBack(cod);
//		} else {
//			System.out.println("error login back - Usuario");
//		}
//	}
	

}
