package com.vista.dato;

// Generated 10-06-2013 10:34:05 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import android.content.ContentValues;

/**
 * Venta generated by hbm2java
 */
public class Venta implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer cod = 10;
	private String nro_venta;
	private String fecha;
	private Integer total_bs;
	private String pago;
	private String fecha_entrega;
	private String ciudad;
	private String deposito;
	private Integer tran;
	private Integer vend;
	private Integer negoc;
	private Integer entregado;
	private String estado;

	public Venta() {

	}

	public Venta(String string) {
		ciudad = string;
	}

	public Venta(Integer cod, String nro_venta, String fecha, Integer total_bs,
			String pago, String fecha_entrega, String ciudad, String deposito,
			int tran, int vend, int negoc, int entregado, String estado) {
		super();
		this.cod = cod;
		this.nro_venta = nro_venta;
		this.fecha = fecha;
		this.total_bs = total_bs;
		this.pago = pago;
		this.fecha_entrega = fecha_entrega;
		this.ciudad = ciudad;
		this.deposito = deposito;
		this.tran = tran;
		this.vend = vend;
		this.negoc = negoc;
		this.entregado = entregado;
		this.estado = estado;
	}

	/**
	 * @return the cod
	 */
	public Integer getCod() {
		return cod;
	}

	/**
	 * @param cod
	 *            the cod to set
	 */
	public void setCod(Integer cod) {
		this.cod = cod;
	}

	/**
	 * @return the nro_venta
	 */
	public String getNro_venta() {
		return nro_venta;
	}

	/**
	 * @param nro_venta
	 *            the nro_venta to set
	 */
	public void setNro_venta(String nro_venta) {
		this.nro_venta = nro_venta;
	}

	/**
	 * @return the fecha
	 */
	public String getFecha() {
		return fecha;
	}

	/**
	 * @param fecha
	 *            the fecha to set
	 */
	public void setFecha(String fecha) {
		this.fecha = fecha;
	}

	/**
	 * @return the total_bs
	 */
	public Integer getTotal_bs() {
		return total_bs;
	}

	/**
	 * @param total_bs
	 *            the total_bs to set
	 */
	public void setTotal_bs(Integer total_bs) {
		this.total_bs = total_bs;
	}

	/**
	 * @return the pago
	 */
	public String getPago() {
		return pago;
	}

	/**
	 * @param pago
	 *            the pago to set
	 */
	public void setPago(String pago) {
		this.pago = pago;
	}

	/**
	 * @return the fecha_entrega
	 */
	public String getFecha_entrega() {
		return fecha_entrega;
	}

	/**
	 * @param fecha_entrega
	 *            the fecha_entrega to set
	 */
	public void setFecha_entrega(String fecha_entrega) {
		this.fecha_entrega = fecha_entrega;
	}

	/**
	 * @return the ciudad
	 */
	public String getCiudad() {
		return ciudad;
	}

	/**
	 * @param ciudad
	 *            the ciudad to set
	 */
	public void setCiudad(String ciudad) {
		this.ciudad = ciudad;
	}

	/**
	 * @return the deposito
	 */
	public String getDeposito() {
		return deposito;
	}

	/**
	 * @param deposito
	 *            the deposito to set
	 */
	public void setDeposito(String deposito) {
		this.deposito = deposito;
	}

	/**
	 * @return the tran
	 */
	public int getTran() {
		return tran;
	}

	/**
	 * @param tran
	 *            the tran to set
	 */
	public void setTran(int tran) {
		this.tran = tran;
	}

	/**
	 * @return the vend
	 */
	public int getVend() {
		return vend;
	}

	/**
	 * @param vend
	 *            the vend to set
	 */
	public void setVend(int vend) {
		this.vend = vend;
	}

	/**
	 * @return the negoc
	 */
	public int getNegoc() {
		return negoc;
	}

	/**
	 * @param negoc
	 *            the negoc to set
	 */
	public void setNegoc(int negoc) {
		this.negoc = negoc;
	}

	/**
	 * @return the entregado
	 */
	public int getEntregado() {
		return entregado;
	}

	/**
	 * @param entregado
	 *            the entregado to set
	 */
	public void setEntregado(int entregado) {
		this.entregado = entregado;
	}

	/**
	 * @return the estado
	 */
	public String getEstado() {
		return estado;
	}

	/**
	 * @param estado
	 *            the estado to set
	 */
	public void setEstado(String estado) {
		this.estado = estado;
	}

	public ContentValues getValues() {

		ContentValues values = new ContentValues();

		values.put("nro_venta", nro_venta);
		values.put("fecha", fecha);
		values.put("total_bs", total_bs);
		values.put("pago", pago);
		values.put("fecha_entrega", fecha_entrega);
		values.put("ciudad", ciudad);
		values.put("deposito", deposito);
		values.put("tran", tran);
		values.put("vend", vend);
		values.put("negoc", negoc);
		values.put("entregado", entregado);
		values.put("estado", estado);
		return values;
	}

	@Override
	public String toString() {
		return ciudad;
	}
}
